class AccountEntity {
  final String id;
  final String name;
  final String currency;

  AccountEntity({required this.id, required this.name, required this.currency});

  // Optional: factory method for creation
  factory AccountEntity.create({
    required String name,
    required String currency,
  }) {
    return AccountEntity(
      id: '', // Will be generated by data layer
      name: name,
      currency: currency,
    );
  }
}
